[project]
name = "iipython-cmd"
version = "1.0.0"
description = "web terminal"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "lxml>=5.4.0",
    "nova-framework>=0.14",
]

[tool.uv.workspace]
members = [
    "backend",
]
